language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
  - pip install pytest pytest-cov

services:
  - postgresql

before_script:
  - psql -c 'create database sendit_test;' -U postgres


script:
  - pytest
  - py.test tests/
  - py.test --cov=app

after_success:
  - coveralls