language: python

python:
  - "3.6"

sudo: required


install:
  - sudo pip install -r requirements.txt
  - sudo pip install coveralls
  - sudo pip install codecov
  - sudo pip install pytest pytest-cov

services:
  - postgresql

before_script:
  - psql -c 'create database sendit_test;' -U postgres



script:
  - pytest
  - py.test tests/
  - py.test --cov=app

after_success:
  - coveralls